In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9537037037037037

In [4]:
svm = SVC(gamma='auto') # arguments given to tune SVC are gamma, kernel, rbf
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.48333333333333334

In [ ]:
dir(SVC())

In [6]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

# split() methods - returns iterator for given list 
# and this "iterator" iterates over the two lists which contains indices of training_data_set
# testing_data_set

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [12]:
# here the difference btn two KFold modules is "StratifiedKFold" module splits the dataset mutually for training and testing with data from every aspects(i.e. from 3 different flower types incase of load_iris())
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3) 

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [13]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [14]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [15]:
scores_rf

[0.9215358931552587, 0.9482470784641068, 0.9115191986644408]

In [17]:
from sklearn.model_selection import cross_val_score # it is used to perform the above task on finding average score in a single method

In [20]:
# parameters for cross_val_score() method
# cross_val_score(algorithm, inputdata, outputdata)
# cross_val_score() uses StratifiedKFold by default
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [34]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=3) 
# cv represents the no. of folds to take on the given dataset

array([0.38063439, 0.41068447, 0.51252087])

In [21]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.93489149, 0.95826377, 0.92654424])

In [30]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.860875232774674

In [31]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9304220980757293

In [32]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=5)
np.average(scores3)

0.9399006828057107

In [35]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=5)
np.average(scores4)

0.9299025069637883

In [29]:
# based on the no. of estimators, RandomForestClassifier results with variable accuracy
# as the no. of estimators increases, accuracy will also increase

In [39]:
scores1 # 10 folds

array([0.80555556, 0.9       , 0.85      , 0.81111111, 0.9       ,
       0.87777778, 0.88888889, 0.89944134, 0.83798883, 0.83798883])

In [38]:
scores4 # 5 folds

array([0.92222222, 0.90277778, 0.94986072, 0.95821727, 0.91643454])